### ISSUE TITLE
effect

### ISSUE THREAD

**Issue by dancerphil** [regionjs/region-core#10]
**Is your feature request related to a problem? Please describe.**
An effect api in order to deal with effect outside view (like React.useEffect).

**Describe the solution you'd like**
```javascript
const cancel = region.effect(['a', 'b'], 'sum', ({a, b}) => a + b);

```javascript
// then you can
region.set('a', 1);
region.set('b', 2);
region.getProps('sum'); // { sum: 3 }

// also forward loading
region.load('a', ...);
region.getProps('sum'); // { loading: true, ... }
```

```javascript
// another case
region.effect('complexObject', 'partA', ({ complexObject }) => complexObject.partA);
region.effect('complexObject', 'partB', ({ complexObject }) => complexObject.partB);

region.load('complexObject', ...);
region.getProps('partA'); // { loading: true, ... }
```

**Describe alternatives you've considered**
```javascript
region.pipe(['a', 'b'], 'sum', ({a, b}) => a + b);
```

**Additional context**
/

**Comment by otakustay** [comment]
1. react的所有`use`不会把dep作为参数提供给callback，我想是有他的设计思想在里面的，region保持和react一致可能是一个选择
2. 不大建议返回cancel这样的模式，固定了返回值，且让返回值是一个很少会用到的东西，会让以后扩展它的功能变麻烦，还是走Cancelation Token模式比较好，或者干脆就不要有cancel的能力
3. 命名上，我认为`computed`和`takeChange`（参考saga）比较形象
4. 其实不建议用在“同步地”级联更新状态上，同步的级联更新应该通过计算（selector）去解决，同步的级联会让状态机变得非常复杂而不易维护，10万行以上的代码里要解析出这些级联关系是非常非常困难的。对于异步的级联我非常推荐
