### ISSUE TITLE
There seems to be a word misspelled here

### ISSUE THREAD

**Issue by yixiaojiu** [regionjs/region-core#94]
https://github.com/regionjs/region-core/blob/f1462ca03eaff343efd51fc5fb412d91495fdbe9/docs/Document.md?plain=1#L78
https://github.com/regionjs/region-core/blob/f1462ca03eaff343efd51fc5fb412d91495fdbe9/docs/Document-zh_CN.md?plain=1#L78

**Comment by dancerphil** [comment]
Thank you for your feedback.
